name: 'project_port_bcn'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  date_of_analysis: CURRENT_DATE


models:
  +transient: false
  project_port_bcn:
    
    bronze: 
      +materialized: view
      +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_BRONZE_DB"
      master_files:
        +schema: master_files
      port_operation:
        +schema: port_operation
      meteo_stations:
        +schema: meteo_stations
    
    silver: #aqui sigue estqndo todq la data temporal
      +materialized: view
      +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_SILVER_DB"
      +schema: core #aqui va a estar todo normalizado al 3 y no consume almacenamiento extra por ser view
      master_files_core:
        intermidiate:
          +materialized: table
          +schema: intermediate
      port_operation_core:
        intermediate:
          +materialized: table
          +schema: intermediate
      meteo_stations_core:
        +materialized: table
      
    gold: 
      +materialized: table
      +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_GOLD_DB"
      daily_ops: #aqui ya los modelos usan la variable de dia llegadas, salidas, buques en puerto (esta variable se cambia para ver estado en otros dias)
        +schema: daily_ops
      analysis: #aqui analisis de procedencias historicas etc
        +schema: analysis  
      meteo: #
        +schema: meteo


snapshots:
  +transient: false
  +target_database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_SILVER_DB"
  master_files_core:
    +target_schema: snapshots
  port_operation_core:
    +target_schema: snapshots